app/models/post.py
from datetime import datetime
from ..extensions import db


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    teacher = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'))
    subject = db.Column(db.String(250))
    student = db.Column(db.Integer)
    date = db.Column(db.DateTime, default=datetime.utcnow)
    updated = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

app/models/user.py
from ..extensions import db, login_manager
from datetime import datetime
from flask_login import UserMixin
from .post import Post


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    posts = db.relationship(Post, backref='author')
    status = db.Column(db.String(50), default='user')
    avatar = db.Column(db.String(200))
    name = db.Column(db.String(50))
    login = db.Column(db.String(50))
    password = db.Column(db.String(200))
    date = db.Column(db.DateTime, default=datetime.utcnow)

app/forms/student.py
from flask_wtf import FlaskForm
from wtforms import SelectField


class StudentForm(FlaskForm):
    student = SelectField('student', choices=[], render_kw={'class': 'form-control'})

app/forms/teacher.py
from flask_wtf import FlaskForm
from wtforms import SelectField


class TeacherForm(FlaskForm):
    teacher = SelectField('teacher', choices=[], render_kw={'class': 'form-control'})

app/forms/user.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, PasswordField, SubmitField, FileField, ValidationError, BooleanField
from wtforms.validators import DataRequired, Length, EqualTo
from ..models.user import User


class RegistrationForm(FlaskForm):
    name = StringField('ФИО', validators=[DataRequired(), Length(min=2, max=100)])
    login = StringField('Логин', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Пароль', validators=[DataRequired()])
    confirm_password = PasswordField('Подтвердите пароль', validators=[DataRequired(), EqualTo('password')])
    avatar = FileField('Загрузите свое фото', validators=[FileAllowed(['jpg', 'jpeg', 'png'])])
    submit = SubmitField('Зарегистрироваться')

    def validate_login(self, field):
        user = User.query.filter_by(login=field.data).first()
        if user:
            raise ValidationError('Пользователь с таким Логином уже существует. Введите уникальный Логин.')


class LoginForm(FlaskForm):
    login = StringField('Логин', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Пароль', validators=[DataRequired()])
    remember = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')

app/__init__.py
from flask import Flask
from datetime import datetime
from .extensions import db, migrate, login_manager
from .config import Config

from .routes.user import user
from .routes.post import post


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    app.jinja_env.globals['now'] = datetime.now

    app.register_blueprint(user)
    app.register_blueprint(post)

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    # LOGIN MANAGER
    login_manager.login_view = 'user.login'
    login_manager.login_message = "Please login to access this page."
    login_manager.login_message_category = 'info'

    with app.app_context():
        db.create_all()

    return app

app/routes/post.py
from flask import Blueprint, abort, request, render_template, redirect, url_for
from flask_login import login_required, current_user
from ..extensions import db
from ..models.post import Post
from ..models.user import User
from ..forms.student import StudentForm
from ..forms.teacher import TeacherForm

post = Blueprint('post', __name__)


@post.route('/', methods=['GET', 'POST'])
def all():
    form = TeacherForm()
    form.teacher.choices = ['Все посты']+[t.name for t in User.query.filter_by(status='teacher')]

    if request.method == 'POST' and request.form['teacher'] != 'Все посты':
        teacher = request.form['teacher']
        teacher_id = User.query.filter_by(name=teacher).first().id
        posts = Post.query.filter_by(teacher=teacher_id).order_by(Post.date.desc()).all()
    else:
        posts = Post.query.order_by(Post.date.desc()).all()
    return render_template('post/all.html',
                           form=form,
                           posts=posts,
                           user=User
                           )


@post.route('/post/create', methods=['GET', 'POST'])
@login_required
def create():
    form = StudentForm()
    form.student.choices = [s.name for s in User.query.filter_by(status='user')]
    if request.method == 'POST':
        subject = request.form.get('subject')
        student = request.form.get('student')
        student_id = User.query.filter_by(name=student).first().id

        post = Post(teacher=current_user.id, subject=subject, student=student_id)

        try:
            db.session.add(post)
            db.session.commit()
            return redirect('/')
        except Exception as e:
            print(str(e))
            return render_template('post/create.html')
    else:
        return render_template('post/create.html', form=form)


@post.route('/post/<int:id>/update', methods=['GET', 'POST'])
@login_required
def update(id):
    post = Post.query.get_or_404(id)
    if post.author.id == current_user.id:
        form = StudentForm()
        form.student.data = User.query.filter_by(id=post.student).first().name
        form.student.choices = [s.name for s in User.query.filter_by(status='user')]
        if request.method == 'POST':
            post.subject = request.form.get('subject')
            student = request.form.get('student')

            post.student = User.query.filter_by(name=student).first().id

            try:
                db.session.commit()
                return redirect('/')
            except Exception as e:
                print(str(e))
                return render_template('post/all.html')
        else:
            return render_template('post/update.html', post=post)
    else:
        # abort(403)
        return render_template('main/_403.html')


@post.route('/post/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete(id):
    post = Post.query.get_or_404(id)
    if post.author.id == current_user.id:
        try:
            db.session.delete(post)
            db.session.commit()
            return redirect(url_for('post.all'))
        except Exception as e:
            print(str(e))
            return str(e)
    else:
        # abort(403)
        return render_template('main/_403.html')

app/routes/user.py
from flask import Blueprint, render_template, redirect, flash, request, url_for
from flask_login import login_user, logout_user

from ..forms.user import RegistrationForm, LoginForm
from ..extensions import db, bcrypt
from ..models.user import User
from ..helpers import save_avatar

user = Blueprint('user', __name__)


@user.route('/user/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            print(form.avatar.data)
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user = User(name=form.name.data,
                        login=form.login.data,
                        avatar=save_avatar(form.avatar.data),
                        password=hashed_password)
            try:
                db.session.add(user)
                db.session.commit()
            except Exception as e:
                print(str(e))
                flash(f"При регистрации произошла ошибка", "danger")

            flash(f"Пользователь {form.name.data} успешно зарегистрирован", "success")
            return redirect(url_for('user.login'))

    return render_template('user/register.html', form=form)


@user.route('/user/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(login=form.login.data).first()
            if user and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                next_page = request.args.get('next')
                flash(f"Вы успешно авторизованы", "success")
                return redirect(next_page) if next_page else redirect(url_for('post.all'))
            else:
                flash(f"Ошибка входа. Проверьте login и пароль.", "danger")
    return render_template('user/login.html', form=form)


@user.route('/user/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('post.all'))

app/templates/main/_403.html
{% extends 'main/base.html' %}

{% block title %}FORBIDDEN{% endblock %}

{% block content %}You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.{% endblock %}

app/templates/main/_flash.html
<!-- FLASH MESSAGES -->
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/main/_footer.html
<ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="#" class="nav-link px-2">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">Pricing</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">About</a></li>
</ul>
<p class="text-center">© {{ now().year }} Company, Inc</p>

app/templates/main/_header.html
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
    <a href="{{ url_for('post.all') }}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <img class="header__img" src="{{ url_for('static', filename='img/student.png') }}" alt="student">
    </a>

    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{{ url_for('post.all') }}" class="nav-link px-2 text-secondary">Главная</a></li>
        {% if current_user.is_authenticated and current_user.status == 'teacher' %}
        <li><a href="{{ url_for('post.create') }}" class="nav-link px-2 text-white">Добавить тему</a></li>
        {% endif %}
    </ul>

    <div class="text-end">
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('user.logout') }}" class="btn btn-outline-light me-2">Выйти</a>
        {% else %}
            <a href="{{ url_for('user.login') }}" class="btn btn-outline-light me-2">Войти</a>
            <a href="{{ url_for('user.register') }}" class="btn btn-warning">Регистрация</a>
        {% endif %}
    </div>
    {% if current_user.is_authenticated %}
    <div class="dropdown text-end">
        <a class="btn btn-outline-primary disabled">{{ current_user.name }}</a>
    </div>
    {% endif %}
</div>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        {% block style %}{% endblock %}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
    <div class="page">
        <header class="header">{% include 'main/_header.html' %}</header>
        {% include 'main/_flash.html' %}
        <main class="content">
            <h1 class="text-center">{{ self.title() }}</h1>
            {% block content %}{% endblock %}
        </main>
            <footer class="py-3 my-4">{% include 'main/_footer.html' %}</footer>
        </div>

        <script src="{{ url_for('static', filename='js/libs/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/app.js') }}"></script>
    </body>
</html>

app/templates/post/all.html
{% extends 'main/base.html' %}

{% block title %}Все темы{% endblock %}

{% block style %}
	<link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/table.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/font-awesome.min.css') }}">
{% endblock %}

{% block content %}
<form method="post" class="form-control d-flex flex-row gap-2">
    {{ form.csrf }}
    {{ form.teacher }}
    <input type="submit" class="btn btn-success" value="Показать">
</form>

<div class="table-responsive custom-table-responsive">
    <table class="table custom-table">
        <thead>
            <tr>
                <th scope="col" class="text-center">ID</th>
                <th scope="col" class="text-center">Преподаватель</th>
                <th scope="col" class="text-center">Тема</th>
                <th scope="col" class="text-center">Студент</th>
                <th scope="col" class="text-center">Действие</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
                <tr scope="row">
                    <td>{{ post.id }}</td>
                    <td>
                        <img width="96px" height="96px" src="{{ url_for('static', filename='upload/'+post.author.avatar) }}" alt="Преподаватель">
                        {{ post.teacher.name }}
                    </td>
                    <td>{{ post.subject }}</td>
                    <td>
                        {% with student = user.query.get(post.student) %}
                            <img width="96px" height="96px" src="{{ url_for('static', filename='upload/'+user.query.get(post.student).avatar) }}" alt="Студент">
                            {{ post.teacher.name }}
                        {% endwith %}
                    </td>
                    <td>
                    {% if current_user.is_authenticated and post.teacher == current_user.id %}
                        <a href="{{ url_for('post.update', id=post.id) }}" class="btn btn-sm btn-secondary"><span class="fa fa-edit"></span></a>
                        <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-sm btn-danger"><span class="fa fa-trash"></span></a>
                    {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/post/create.html
{% extends 'main/base.html' %}

{% block title %}Добавление темы{% endblock %}

{% block content %}
<form method="post" class="form-control d-flex flex-column gap-2 bg-dark">
    <input name="subject" type="text" placeholder="Тема" class="form-control">
    {{ form.student }}
    <input value="Добавить" type="submit"class="btn btn-success" >
</form>
{% endblock %}

app/templates/post/update.html
{% extends 'main/base.html' %}

{% block title %}Редактирование темы {{ post.subject }}{% endblock %}

{% block content %}
<form method="post" class="form-control d-flex flex-column gap-2 bg-dark">
    <input value="{{ post.subject }}" name="subject" type="text" placeholder="Тема" class="form-control">
    <input value="{{ post.student }}" name="student" type="text" placeholder="ФИО студента" class="form-control">
    <input value="Обновить" type="submit"class="btn btn-success" >
</form>
{% endblock %}

app/templates/user/login.html
{% extends 'main/base.html' %}

{% block title %}Авторизация{% endblock %}

{% block content %}
    <form method="post" class="form-control d-flex flex-column gap-2">
        {{ form.csrf_token }}
        {{ form.login(class="form-control", placeholder="Логин") }}

        {{ form.password(class="form-control", placeholder="Пароль") }}
        <div class="d-flex flex-row justify-content-center gap-2">
        {{ form.remember.label }}{{ form.remember(class="form-check") }}
        </div>
        {{ form.submit(class="form-control btn btn-success") }}
    </form>
{% endblock %}

app/templates/user/register.html
{% extends 'main/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" class="form-control d-flex flex-column gap-2">
        {{ form.csrf_token }}
        {{ form.name(class="form-control", placeholder="ФИО") }}

        {% if form.login.errors %}
            <div class="invalid-feedback" style="display: block!important;">
            {% for error in form.login.errors %}
                <span>{{ error }}</span>
            {% endfor %}
            </div>
        {% endif %}
        {{ form.login(class="form-control", placeholder="Логин") }}

        {{ form.avatar(class="form-control btn btn-secondary") }}
        {{ form.password(class="form-control", placeholder="Пароль") }}
        {{ form.confirm_password(class="form-control", placeholder="Подтвердите пароль") }}
        {{ form.submit(class="form-control btn btn-success") }}
    </form>
{% endblock %}